### ISSUE TITLE
Parse stack from WDT resets

### ISSUE THREAD

**Issue by fcouceiro** [janLo/EspArduinoExceptionDecoder#2]
I'm trying to parse a stack trace dumped from a soft WDT reset and it is throwing this error:
`ERROR: Parser not complete!`

The content of the file I'm feeding in is:

```
Soft WDT reset

ctx: sys
sp: 3ffff950 end: 3fffffb0 offset: 01b0

>>>stack>>>
3ffffb00:  3ffffb88 00000000 00000010 401009d7

< collapsed a bunch of lines >

3fffffa0:  40000f49 3fffdab0 3fffdab0 40000f49
<<<stack<<<
```

I had success decoding other type of exceptions.

Thanks!

**Comment by janLo** [comment]
That is because it is not an Exception, its a `Soft WDT reset`.

If you have only a stacktrace (without an exception) you can decode it using the `--stack_only` (or short `-s`) option.

**Comment by fcouceiro** [comment]
Working nicely. Thank you!

**Comment by g01d10x** [comment]
Hi there, thanks for this python version of the stack trace .. could you please post an example of using the -s option?
