### ISSUE TITLE
.... at ??:?

### ISSUE THREAD

**Issue by amir-hg** [janLo/EspArduinoExceptionDecoder#7]
hi
I could decode the stack but the end of all of my results is like at ??:?

ubuntu 18.04 LTS
PlatformIO 3.6.2
espressif8266 1.8.0
ESP8266

**Comment by janLo** [comment]
This sounds like the (debug-)information is just missing from the binary.

**Comment by amir-hg** [comment]
Do you have any suggestion to fix it ?

**Comment by janLo** [comment]
In your platformio.ini in the environemt put:
```
build_flags = -ggdb3
```
or at least:
```
build_flags = -g
```
This *should* not affect the built firmware as this gets stripped anyway.
